### ISSUE TITLE
Running demo gives an error

### ISSUE THREAD

**Issue by Karhide** [HKU-BAL/CONNET#3]
```
ubuntu@ip-10-156-11-150:~/CONNET/ecoli_demo$` python2 $CONNET ../models/ecoli.model1 ../models/ecoli.model2 ../sample_data/ecoli_raw_reads.fq ../sample_data/ecoli_draft_assembly.fa
[2020-05-18 13:24:35.115884] Round 0 begins
[M::mm_idx_gen::0.211*0.98] collected minimizers
[M::mm_idx_gen::0.279*2.26] sorted minimizers
[M::main::0.279*2.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.307*2.15] mid_occ = 7
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.325*2.08] distinct minimizers: 837002 (98.78% are singletons); average occurrences: 1.016; average spacing: 5.354
ERROR: failed to open file 'input.fa'
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont -t 24 0.fa input.fa
[M::main] Real time: 0.333 sec; CPU: 0.684 sec; Peak RSS: 0.055 GB
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aav 2100001 2200000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aax 2300001 2400000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaw 2200001 2300000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aap 1500001 1600000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aar 1700001 1800000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aau 2000001 2100000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aas 1800001 1900000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aat 1900001 2000000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaq 1600001 1700000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aag 600001 700000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aab 100001 200000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aah 700001 800000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaf 500001 600000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aal 1100001 1200000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aad 300001 400000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aak 1000001 1100000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aai 800001 900000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaj 900001 1000000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aae 400001 500000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aac 200001 300000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aam 1200001 1300000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aao 1400001 1500000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaa 1 100000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aan 1300001 1400000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abt 4500001 4552209']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aaz 2500001 2600000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aba 2600001 2700000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abc 2800001 2900000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abd 2900001 3000000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c aay 2400001 2500000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abb 2700001 2800000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abf 3100001 3200000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abe 3000001 3100000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abg 3200001 3300000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abl 3700001 3800000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abi 3400001 3500000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abk 3600001 3700000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abj 3500001 3600000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abh 3300001 3400000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abq 4200001 4300000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abm 3800001 3900000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abn 3900001 4000000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abp 4100001 4200000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abr 4300001 4400000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abo 4000001 4100000']
[mpileup] 1 samples in 1 input files
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abs 4400001 4500000']
[mpileup] 1 samples in 1 input files
0.utg000001c.phase1.fa
[faidx] Could not build fai index 0.phase1.fa.fai
[WARNING] the length database sequence 'utg000001c' is 0
[M::mm_idx_gen::0.002*0.00] collected minimizers
[M::mm_idx_gen::0.006*4.08] sorted minimizers
[M::main::0.006*4.05] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*4.00] mid_occ = 569556073
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*3.95] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
ERROR: failed to open file 'input.fa'
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x map-ont -t 24 0.phase1.fa input.fa
[M::main] Real time: 0.007 sec; CPU: 0.024 sec; Peak RSS: 0.008 GB
[faidx] Could not build fai index 0.phase1.fa.fai
Traceback (most recent call last):
  File "/home/ubuntu/CONNET/split_job.py", line 24, in <module>
    faidx = open("%s.fa.fai" % R).read().splitlines()
IOError: [Errno 2] No such file or directory: '0.phase1.fa.fai'
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

parallel: Error: Cannot open input file `0.phase1.parallel': No such file or directory.
```

Thanks!

**Comment by Beauty9527** [comment]
(CONNET) wrs@DESKTOP-M954BBE:~/CONNET/ecoli_demo$ python2 $CONNET ../models/ecoli.model1 ../models/ecoli.model2 ../sample_data/ecoli_raw_reads.fq ../sample_data/ecoli_draft_assembly.fa
  File "../models/ecoli.model1", line 1
SyntaxError: Non-ASCII character '\xef' in file ../models/ecoli.model1 on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Would you please tell me which code model1 has used to encode? Is that HDF5 file? And how to open it?
Thanks!

**Comment by Beauty9527** [comment]
Dear Karhide,
        I have met the same problem "Failed to open the 'input_data'", maybe the problem is the loss of "ecoli_raw_reads.fq" in sample_data.Have you fix this,would you please tell me how?

Thanks!

**Comment by bbvan** [comment]
@Karhide 
It seems the alignment step at the beginning failed due to missing/invalid files (`ERROR: failed to open file 'input.fa'`)

Could you please check the file `input.fa`? It should be a symlink to your input file `../sample_data/ecoli_raw_reads.fq`.

**Comment by Beauty9527** [comment]
Dear Sir，
             There is a file named "../sample_data/ecoli_raw_reads.fq", but is just 1 kb size. Is this a resonable .fq document?
Thanks for your reply.

**Comment by bbvan** [comment]
@Beauty9527 
Please remove the 1kb file and use the provided script ([link](https://github.com/HKU-BAL/CONNET/blob/master/sample_data/download.sh)) to prepare sample data.

**Comment by Beauty9527** [comment]
Dear Sir，
        I have run the master-piece successfully as following your word. Thank you very much！
        Have a nice day！

**Comment by Beauty9527** [comment]
Dear Sir，
I have run the master-piece successfully as following your words. And there is a new warning"taskset: failed to set pid 274's affinity: Invalid argument". Will this affect the output?
Thank you very much！
Have a nice day！
