### ISSUE TITLE
Specify the version of tensorflow required

### ISSUE THREAD

**Issue by Karhide** [HKU-BAL/CONNET#4]
Pip will usually default to installing v2.0+, but I encountered an error with that version, which went away when I downgraded to v1.13.1.

```
Using TensorFlow backend.
Phase 1 with param ['0 utg000001c abn 3900001 4000000']
Traceback (most recent call last):
  File "/home/ubuntu/CONNET//phase1.py", line 49, in <module>
    main()
  File "/home/ubuntu/CONNET//phase1.py", line 28, in main
    session_conf = tf.ConfigProto( intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)
AttributeError: 'module' object has no attribute 'ConfigProto'
```

**Comment by bbvan** [comment]
Thanks for the advice! Readme has been updated to include Python package versions.
